spring:
  datasource:
    url: jdbc:mysql://db:3306/springdata?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
  application:
    name: trello
server:
  port: 8080
